import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import sveltePlugin from "esbuild-svelte";
import { sveltePreprocess } from 'svelte-preprocess';
import fs from "fs"; // Added fs import

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// Custom plugin to rename main.css -> styles.css
const moveStyles = {
	name: 'move-styles',
	setup(build) {
		build.onEnd(() => {
			if (fs.existsSync('main.css')) {
				fs.renameSync('main.css', 'styles.css');
				console.log('Moved main.css to styles.css');
			}
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	plugins: [
		sveltePlugin({
			compilerOptions: {
				dev: true,
				css: 'external',
				runes: true,
			},
			preprocess: sveltePreprocess({
				typescript: true
			}),
		}),
		moveStyles
	],
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}